// POST /api/playlist/save — creates a playlist on the authed user's account
// and fills it with the provided track URIs.

const express = require('express');

const requireAuth = require('../middleware/requireAuth');
const {
  getMe,
  createPlaylist,
  addTracksToPlaylist,
} = require('../services/spotifyService');

const router = express.Router();

router.post('/save', requireAuth, async (req, res, next) => {
  try {
    const {
      name = 'Vibe Playlist',
      description = 'Generated by Vibe Playlist Generator',
      isPublic = false,
      uris = [],
    } = req.body || {};

    if (!Array.isArray(uris) || !uris.length) {
      return res
        .status(400)
        .json({ error: 'no_tracks', message: 'uris must be a non-empty array of Spotify track URIs.' });
    }

    // Spotify caps the description at ~300 chars.
    const safeDescription = String(description).slice(0, 280);

    const me = await getMe(req.accessToken);
    const playlist = await createPlaylist(req.accessToken, me.id, {
      name: String(name).slice(0, 100),
      description: safeDescription,
      isPublic,
    });

    await addTracksToPlaylist(req.accessToken, playlist.id, uris);

    res.json({
      id: playlist.id,
      name: playlist.name,
      url: playlist.external_urls?.spotify,
      trackCount: uris.length,
    });
  } catch (err) {
    next(err);
  }
});

module.exports = router;
