require('dotenv').config();
const express = require('express');
const session = require('express-session');
const cookieParser = require('cookie-parser');
const cors = require('cors');
const config = require('./src/config');
const authRouter = require('./src/routes/auth');
const recsRouter = require('./src/routes/recommendations');
const playlistRouter = require('./src/routes/playlist');
const errorHandler = require('./src/middleware/errorHandler');
const app = express();
app.use(cors({ origin: true, credentials: true }));
app.use(express.json());
app.use(cookieParser());
app.use(session({ name: 'vibe.sid', secret: config.sessionSecret, resave: false, saveUninitialized: false, cookie: { httpOnly: true, sameSite: 'lax', secure: false, maxAge: 86400000 } }));
app.get('/', (req, res) => { res.type('html').send(PAGE); });
app.get('/api/health', (req, res) => res.json({ ok: true }));
app.use('/api/auth', authRouter);
app.use('/api/recommendations', recsRouter);
app.use('/api/playlist', playlistRouter);
app.use(errorHandler);
app.listen(config.port, () => console.log('[vibe] listening on :' + config.port));

const PAGE = `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vibe Playlist Generator</title><style>*{box-sizing:border-box;margin:0;padding:0}body{background:#0b0c0f;color:#e9ecf1;font-family:-apple-system,sans-serif;padding:30px}a{color:#ff6a3d}.box{max-width:900px;margin:0 auto}.hd{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px;flex-wrap:wrap;gap:10px}.hd h1{font-size:20px}.hd small{color:#8a93a6;font-size:12px;display:block}select,input[type=text]{padding:8px;background:#181b22;color:#e9ecf1;border:1px solid #2a2f3a;border-radius:6px;font-size:14px;width:100%;margin-bottom:10px}label{display:block;font-size:11px;color:#8a93a6;margin-bottom:4px;text-transform:uppercase;letter-spacing:.5px}.btn{padding:12px 20px;background:#ff6a3d;color:#111;border:none;border-radius:7px;font-weight:700;cursor:pointer;font-size:14px;width:100%;margin-bottom:8px}.btn:hover{filter:brightness(1.08)}.btn:disabled{opacity:.5}.btn2{background:transparent;color:#e9ecf1;border:1px solid #2a2f3a}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.card{display:flex;gap:12px;align-items:center;border:1px solid #2a2f3a;border-radius:8px;padding:10px;margin-bottom:8px}.card img{width:50px;height:50px;border-radius:5px;background:#21252e}.card .nm{font-weight:600;font-size:14px}.card .ar{font-size:12px;color:#8a93a6}.msg{text-align:center;padding:40px;color:#8a93a6}.msg h3{color:#e9ecf1;margin-bottom:8px}.err{color:#ff5a5a;padding:10px;border:1px solid #ff5a5a;border-radius:6px;margin-bottom:10px}.ok{color:#8ef0c0;padding:10px;border:1px solid #8ef0c0;border-radius:6px;margin-bottom:10px}.pills{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:12px}.pill{font-size:11px;padding:3px 8px;border:1px solid #2a2f3a;border-radius:99px;color:#8a93a6}.pill.a{color:#ff6a3d;border-color:#ff6a3d}#form,#res{background:#121419;border:1px solid #2a2f3a;border-radius:10px;padding:20px}.grid{display:grid;grid-template-columns:320px 1fr;gap:20px}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style></head><body><div class="box"><div class="hd"><div><h1>Vibe Playlist Generator</h1><small>Afro House · Melodic Tech · Deep House</small></div><div id="prof"></div></div><div id="main"></div></div><script>
let me=null,busy=false,err=null,result=null,saved=null;
async function api(p,o={}){const r=await fetch(p,{method:o.method||'GET',headers:o.body?{'Content-Type':'application/json'}:void 0,body:o.body?JSON.stringify(o.body):void 0});const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={raw:t}}if(!r.ok){const e=new Error(d?.message||d?.error||r.statusText);e.status=r.status;throw e}return d}
function render(){
document.getElementById('prof').innerHTML=me?'<span style="color:#8a93a6;font-size:13px">'+me.displayName+' </span><button class="btn2" style="width:auto;padding:4px 10px;font-size:12px;border-radius:5px;cursor:pointer;background:transparent;color:#e9ecf1;border:1px solid #2a2f3a" onclick="logout()">Log out</button>':'';
if(!me){document.getElementById('main').innerHTML='<div class="msg"><h3>Connect Spotify to start</h3><p style="margin-bottom:16px">Generate curated playlists with one click.</p><a class="btn" style="display:inline-block;width:auto;padding:12px 28px;text-decoration:none" href="/api/auth/login">Connect Spotify</a></div>';return}
document.getElementById('main').innerHTML='<div class="grid"><div id="form"><h3 style="font-size:13px;color:#8a93a6;text-transform:uppercase;letter-spacing:1px;margin-bottom:14px">Vibe</h3><label>Genre</label><select id="g"><option value="afro-house">Afro House</option><option value="melodic-tech">Melodic Tech</option><option value="deep-house">Deep House</option><option value="organic-house">Organic House</option></select><label>Mood</label><select id="m"><option>hypnotic</option><option>emotional</option><option>dark</option><option>uplifting</option><option>dreamy</option><option>driving</option><option>warm</option></select><label>Artist Seed (optional)</label><input type="text" id="as" placeholder="e.g. Keinemusik"><label>Label Mode</label><select id="lb"><option value="">— none —</option><option value="moblack">MoBlack Records</option><option value="keinemusik">Keinemusik</option><option value="dawn-patrol">Dawn Patrol</option></select><div style="margin:10px 0"><label style="display:flex;gap:6px;align-items:center;cursor:pointer"><input type="checkbox" id="ug" style="accent-color:#ff6a3d"> <span>Underground bias</span></label></div><div style="height:1px;background:#2a2f3a;margin:14px 0"></div><button class="btn" onclick="gen()" '+(busy?'disabled':'')+'>Generate Playlist</button><button class="btn btn2" onclick="dj()" '+(busy?'disabled':'')+'>DJ Set Mode</button></div><div id="res"><h3 style="font-size:13px;color:#8a93a6;text-transform:uppercase;letter-spacing:1px;margin-bottom:14px">Result</h3>'+(err?'<div class="err">'+err+'</div>':'')+(saved?'<div class="ok">Saved! <a href="'+saved.url+'" target="_blank">Open in Spotify</a></div>':'')+(!result&&!busy?'<div class="msg"><h3>No playlist yet</h3><p>Pick a vibe and generate.</p></div>':'')+(busy&&!result?'<div class="msg"><h3>Generating...</h3></div>':'')+(result?rr():'')+'</div></div>'}
function rr(){const{tracks:t,meta:m}=result;let h='<div class="pills">';if(m?.genre)h+='<span class="pill a">'+m.genre+'</span>';if(m?.mood)h+='<span class="pill">'+m.mood+'</span>';if(m?.djSet)h+='<span class="pill">DJ Set</span>';h+='</div>';if(!t||!t.length)return h+'<div class="err">No tracks found. Try different settings.</div>';h+='<button class="btn" onclick="sav()">Save to My Spotify</button>';for(const i of t){const k=i.track;h+='<div class="card"><img src="'+(k.album?.image||'')+'" onerror="this.style.visibility=\\'hidden\\'"><div><div class="nm"><a href="'+(k.url||'#')+'" target="_blank" style="color:#e9ecf1">'+k.name+'</a></div><div class="ar">'+(k.artists||[]).map(a=>a.name).join(', ')+'</div></div></div>'}return h}
function gf(){return{genre:el('g'),mood:el('m'),artistSeed:el('as')||void 0,label:el('lb')||null,underground:document.getElementById('ug')?.checked,limit:20}}
function el(id){return document.getElementById(id)?.value}
async function gen(){busy=true;err=null;result=null;saved=null;render();try{result=await api('/api/recommendations/generate',{method:'POST',body:gf()})}catch(e){err=e.message;if(e.status===401)me=null}busy=false;render()}
async function dj(){busy=true;err=null;result=null;saved=null;render();try{result=await api('/api/recommendations/dj-set',{method:'POST',body:{...gf(),length:30}})}catch(e){err=e.message;if(e.status===401)me=null}busy=false;render()}
async function sav(){if(!result?.tracks?.length)return;busy=true;err=null;render();try{const u=result.tracks.map(t=>t.track.uri).filter(Boolean);const n=[result.meta?.genre,result.meta?.mood].filter(Boolean).join(' - ');saved=await api('/api/playlist/save',{method:'POST',body:{name:n||'Vibe Playlist',uris:u}})}catch(e){err=e.message}busy=false;render()}
async function logout(){await api('/api/auth/logout',{method:'POST'});me=null;result=null;saved=null;render()}
async function init(){try{me=await api('/api/auth/me')}catch{}render()}
init();
</script></body></html>`;
